title: "Ing. Jozef Výbošťok PhD."
description: "3D skenovanie, LiDAR a výskum lesných ekosystémov"
url: "https://jozefvybostok.github.io"
baseurl: ""

# použijeme oficiálnu GitHub Pages tému minima
theme: minima

# vypneme remote_theme a pluginy SCSS, aby build nikdy nepadol
# remote_theme: alshedivat/al-folio
# plugins:
#   - jekyll-remote-theme
